IC Travel : Page Update
clicepfl/clic-website pull request #358
Opened 2023-02-21 13:28 UTC by Christelle13

2023-02-21 13:51 UTC, NoeTerrier approved these changes

2023-02-21 15:27 UTC, Robb-Fr requested changes
Add Alexi's pic

2023-02-21 15:27 UTC, Robb-Fr commented on src/pages/commissions/assets/ic-travel.md
> +Pour s'inscrire au voyage, c'est par [ICI](https://docs.google.com/forms/d/e/1FAIpQLSdIapeE55ba2bNiv1UlK6nTi_ozvoxy_VjLTFZ7yKLWZD9HSw/viewform?usp=sf_link)
Je te conseille de mettre dans un lien https://go.epfl.ch pour être flexible en cas de besoin

2023-02-21 15:51 UTC, Robb-Fr requested changes
Mets dans un go epfl, mieux vaut le faire tout de suite plutot que trop tard

2023-02-21 15:51 UTC, Robb-Fr commented on src/pages/commissions/assets/ic-travel.md
> +Pour s'inscrire au voyage, c'est par [ICI](https://docs.google.com/forms/d/e/1FAIpQLSdIapeE55ba2bNiv1UlK6nTi_ozvoxy_VjLTFZ7yKLWZD9HSw/viewform?usp=sf_link)
^

2023-02-23 18:01 UTC, Robb-Fr approved these changes
Local build passes

2023-02-23 18:01 UTC, merged