Update committe list of CEVE and IC Travel commissions
clicepfl/clic-website pull request #414
Opened 2024-02-24 18:17 UTC by mche3kek

Committees for the 23-24 academic year

2024-02-26 11:41 UTC, NoeTerrier requested changes
The pictures need to be squared or the css need to be updated to handle not squared pictures.
![image](https://github.com/clicepfl/clic-website/assets/56764430/85d0957b-4412-48eb-ba80-abee8c602e00)

2024-02-26 11:43 UTC, NoeTerrier commented
No change of the content of the commissions pages ? The year of and destination of IC Travel isn't good anymore :eyes:

2024-02-29 02:50 UTC, mche3kek commented
> No change of the content of the commissions pages ? The year of and destination of IC Travel isn't good anymore 👀

pics and change of content done !

2024-02-29 08:13 UTC, Thechi2000 approved these changes

2024-02-29 08:16 UTC, merged